Ext.define('App.model.pygrjh.PYGRJHKCModel',{
	extend:'Ext.data.Model',
	fields:[
		{name:'id'},{name:'xh'},{name:'nj'},{name:'zydm'},{name:'bbh'},{name:'pyfah'},
		{name:'kch'},{name:'kcmc'},{name:'kclbm'},
		{name:'kclb'},{name:'kcxzm'},{name:'kcxz'},{name:'kcsxm'},{name:'kcsx'},
		{name:'kcxf'},{name:'xslxm'},{name:'xslx'},{name:'zxs'},{name:'llxs'},
		{name:'syxs'},{name:'ksxsm'},{name:'ksxs'},{name:'kkxq'},{name:'kkdwh'},{name:'dwmc'},
		{name:'sfyx'}
	]
})