Ext.define('App.model.pygrjh.ViewPyGrjhModel',{
	extend:'Ext.data.Model',
	fields:[
		{name:'id'},{name:'xh'},{name:'xm'},{name:'nj'},
		{name:'yxsh'},{name:'fymc'},{name:'zydm'},
		{name:'zymc'},{name:'pyccm'},{name:'pycc'},
		{name:'xwlb'},{name:'jylb'},{name:'xslx'},
		{name:'dsh'},{name:'dsxm'},{name:'pyfah'},
		{name:'ztm'},{name:'zt'}
	]
})