Ext.define('App.model.pyfa.PYFAModel',{
	extend:'Ext.data.Model',
	fields:[
		{name:'id'},{name:'bbh'},{name:'pyfah'},{name:'pyfamc'},
		{name:'zydm'},{name:'zymc'},{name:'xz'},{name:'xxnx'},
		{name:'xslxm'},{name:'xslx'},{name:'dwh'},{name:'dwmc'},
		{name:'xwkxf'},{name:'zxf'},{name:'fjdz'},{name:'ztm'},
		{name:'zt'},{name:'sfyx'},{name:'bz'},{name:'pyfsm'},{name:'pyfs'},{name:'bzrgh'},{name:'bzr'}
	]
})